version: '3.9'

services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource

  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
